### ISSUE TITLE
cannot find module http-proxy-middleware

### ISSUE THREAD

**Issue by grvs1404** [angeldeejay/MMM-WyzeBridge#1]
Hello, 
I installed this module and got the error
[11.02.2023 13:43.14.349] [ERROR] App threw an error during load
[11.02.2023 13:43.14.355] [ERROR] Error: Cannot find module 'http-proxy-middleware'
Require stack:
- /home/pi/MagicMirror/modules/MMM-WyzeBridge/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-WyzeBridge/node_helper.js:10:35)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
[11.02.2023 13:43.14.358] [ERROR] Whoops! There was an uncaught exception...
[11.02.2023 13:43.14.378] [ERROR] Error: Cannot find module 'http-proxy-middleware'
Require stack:
- /home/pi/MagicMirror/modules/MMM-WyzeBridge/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-WyzeBridge/node_helper.js:10:35)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-WyzeBridge/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[11.02.2023 13:43.14.379] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[11.02.2023 13:43.14.380] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[11.02.2023 13:43.17.378] [LOG]   Launching application.
[136825:0211/134331.667973:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[136857:0211/134335.320683:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
...
[11.02.2023 13:46.17.955] [ERROR] Whoops! There was an uncaught exception...
[11.02.2023 13:46.18.019] [ERROR] TypeError: Cannot read properties of undefined (reading 'close')
    at App.stop (/home/pi/MagicMirror/js/app.js:274:14)
    at App.<anonymous> (/home/pi/MagicMirror/js/electron.js:159:7)
    at App.emit (node:events:513:28)
    at appMethod (node:electron/js2c/browser_init:2:24153)
    at Object.execute (node:electron/js2c/browser_init:2:28291)
    at MenuItem.click (node:electron/js2c/browser_init:2:30120)
    at a._executeCommand (node:electron/js2c/browser_init:2:35562)

is module http-proxy-middleware required for this module to work?

**Comment by angeldeejay** [comment]
`npm install` within module folder should resolve your issue
